### ISSUE TITLE
error messages in docker logs

### ISSUE THREAD

**Issue by marcwaz** [QuantumObject/docker-mywebsql#4]
My environment is Ubuntu 16.04 + Docker 17.06.2-ce

I noticed the following erros messages with the docker logs command:

Starting pre-service scritps in /etc/my_init.d
*** Running: /etc/my_init.d/startup.sh
/sbin/my_init: line 21: export: `430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A': not a valid identifier
/sbin/my_init: line 21: export: `4D1BB29D63D98E422B2113B19334A25F8507EFA5': not a valid identifier
/sbin/my_init: line 21: export: `430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A': not a valid identifier
/sbin/my_init: line 21: export: `4D1BB29D63D98E422B2113B19334A25F8507EFA5': not a valid identifier
starting rc.local scritps
*** Running: /etc/rc.local
/sbin/my_init: line 21: export: `430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A': not a valid identifier
/sbin/my_init: line 21: export: `4D1BB29D63D98E422B2113B19334A25F8507EFA5': not a valid identifier
/sbin/my_init: line 21: export: `430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A': not a valid identifier
/sbin/my_init: line 21: export: `4D1BB29D63D98E422B2113B19334A25F8507EFA5': not a valid identifier
Booting runit daemon...
Process runsvdir running with PID 546

**Comment by angelrr7702** [comment]
yes, I believe that error is a problem with quantumobject/docker-baseimage .. that this container used .. that fail to assigned two value to a variable ... creating new build for the container that maybe fix it .

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
that fail Ubuntu 15.10 end of life ... no more update ..  need to change this to newer Ubuntu version.

**Comment by angelrr7702** [comment]
build done now still using Ubuntu 15.10 I will update latter to last LTS. please let me know if error msg still present ..

**Comment by marcwaz** [comment]
I confirm. The pb is solved. Thx!
